---
apiVersion: v1
kind: Service
metadata:
  name: coopr-hq-webapp
  labels:
    app: coopr-hq-webapp
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: coopr-hq-webapp
